namespace ChatService.Models
{
    public class ChatHistoryModel
    {
        /// <summary>
        /// Unique identifier for the chat history entry.
        /// </summary>
        public string Id { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// Timestamp when the entry was created.
        /// </summary>
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Message sent by the user.
        /// </summary>
        public string UserMessage { get; set; } = string.Empty;

        /// <summary>
        /// Response generated by the LLM.
        /// </summary>
        public string LLMResponse { get; set; } = string.Empty;

        /// <summary>
        /// SQL query executed during the interaction.
        /// </summary>
        public string SqlQuery { get; set; } = string.Empty;

        /// <summary>
        /// Results of the executed SQL query.
        /// </summary>
        public string QueryResults { get; set; } = string.Empty;

        /// <summary>
        /// Model used for the interaction.
        /// </summary>
        public string Model { get; set; } = string.Empty;

        /// <summary>
        /// Indicates whether the operation was successful.
        /// </summary>
        public bool IsSuccessful { get; set; }

        /// <summary>
        /// Error message if the operation failed.
        /// </summary>
        public string? ErrorMessage { get; set; }
    }
}
